# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=15)),
                ('breed', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
